# Generated by Django 4.1.5 on 2023-03-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0003_generation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='width',
            new_name='weight',
        ),
    ]
