# Generated by Django 4.1.5 on 2023-03-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0005_pokemon_abilities_pokemon_generation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='abilities',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='pkm_types',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.ManyToManyField(to='pokemons.pkmability'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pkm_types',
            field=models.ManyToManyField(to='pokemons.pkmtype'),
        ),
    ]
